---

- name: Copy templates Python
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ _python.templates | default({}) }}"
  when: _python.templates is defined
