---

- name: Install python package dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  register: install_python_package_dependencies
  when: _python_package_dependencies is defined
  with_items: "{{ _python_package_dependencies | default([]) }}"
  tags:
    - dependences
