---

- include: install.d/CentOS.yaml
  when:
    - ansible_distribution == "CentOS"

- include: install.d/Ubuntu.yaml
  when:
    - ansible_distribution == "Ubuntu"

- name: Install python PyEnv
  git:
    repo: "{{ _python_pyenv_repo }}"
    dest: "{{ python_pyenv_path }}"
    update: "{{ python_pyenv_update_git_install }}"
    version: master
  become: true
  become_user: "{{ python_pyenv_owner }}"

- name: Install python PyEnv-virtualenv plugin
  git:
    repo: "{{ _python_pyenv_virtualenv_repo }}"
    dest: "{{ python_pyenv_path }}/plugins/pyenv-virtualenv"
    update: "{{ python_pyenv_update_git_install }}"
    version: master
  become: true
  become_user: "{{ python_pyenv_owner }}"

# - name: Install python PyEnv Up
#   git:
#     repo: "{{ python_pyenv_path }}/plugins/python-build"
#     update: "{{ python_pyenv_update_git_install }}"
#     version: master
#   become: true
#   become_user: "{{ python_pyenv_owner }}"
